class Autogenerated {
  late String s0LegalNotice;
  late int jobCount;
  late List<Jobs> jobs = [];
  Autogenerated({
    required this.s0LegalNotice,
    required this.jobCount,
    required this.jobs,
  });

  // Autogenerated({this.s0LegalNotice, this.jobCount, this.jobs});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    s0LegalNotice = json['0-legal-notice'];
    jobCount = json['job-count'];
    if (json['jobs'] != null) {
      // jobs = new List<Jobs>();
      // List<Jobs> jobs = [];
      json['jobs'].forEach((v) {
        jobs.add(new Jobs.fromJson(v));
      });
      print('job i length ${jobs.length}');
    }
  }
  // List<Jobs> get item {
  //   return [...jobs];
  // }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['0-legal-notice'] = this.s0LegalNotice;
    data['job-count'] = this.jobCount;
    // ignore: unnecessary_null_comparison
    if (this.jobs != null) {
      data['jobs'] = this.jobs.map((v) => v.toJson()).toList();
    }
    return data;
  }
}

class Jobs {
  late int id;
  late String name;
  late String slug;
  Jobs({
    required this.id,
    required this.name,
    required this.slug,
  });

  // Jobs({this.id,this.name,this.slug});

  Jobs.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    slug = json['slug'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['slug'] = this.slug;
    return data;
  }
}
