class Autogenerated2 {
 late String s0LegalNotice;
 late int jobCount;
  List<Jobs> jobs=[];
  Autogenerated2({
    required this.s0LegalNotice,
    required this.jobCount,
    required this.jobs,
  });

  // Autogenerated2({this.s0LegalNotice, this.jobCount, this.jobs});

  // Autogenerated2.fromJson(Map<String, dynamic> json) {
  //   s0LegalNotice = json['0-legal-notice'];
  //   jobCount = json['job-count'];
  //   if (json['jobs'] != null) {
  //     // jobs = new List<Jobs>();
  //     json['jobs'].forEach((v) {
  //       jobs.add(new Jobs.fromJson(v));
  //     });
  //   }
  // }

  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['0-legal-notice'] = this.s0LegalNotice;
  //   data['job-count'] = this.jobCount;
  //   if (this.jobs != null) {
  //     data['jobs'] = this.jobs.map((v) => v.toJson()).toList();
  //   }
  //   return data;
  // }
}

class Jobs {
 late int id;
 late String url;
 late String title;
 late String companyName;
 late String category;
//  late List<Null> tags;
 late String jobType;
 late String publicationDate;
 late String candidateRequiredLocation;
 late String salary;
 late String description;
//  late String companyLogoUrl;

  Jobs(
      {
    required  this.id,
    required  this.url,
    required  this.title,
    required  this.companyName,
    required  this.category,
    // required  this.tags,
    required  this.jobType,
    required  this.publicationDate,
    required  this.candidateRequiredLocation,
    required  this.salary,
    required  this.description,
    // required  this.companyLogoUrl
    });

  // Jobs.fromJson(Map<String, dynamic> json) {
  //   id = json['id'];
  //   url = json['url'];
  //   title = json['title'];
  //   companyName = json['company_name'];
  //   category = json['category'];
  //   if (json['tags'] != null) {
  //     // tags = new List<Null>();
  //     json['tags'].forEach((v) {
  //       tags.add(new Null.fromJson(v));
  //     });
  //   }
  //   jobType = json['job_type'];
  //   publicationDate = json['publication_date'];
  //   candidateRequiredLocation = json['candidate_required_location'];
  //   salary = json['salary'];
  //   description = json['description'];
  //   companyLogoUrl = json['company_logo_url'];
  // }

  // Map<String, dynamic> toJson() {
  //   final Map<String, dynamic> data = new Map<String, dynamic>();
  //   data['id'] = this.id;
  //   data['url'] = this.url;
  //   data['title'] = this.title;
  //   data['company_name'] = this.companyName;
  //   data['category'] = this.category;
  //   if (this.tags != null) {
  //     // data['tags'] = this.tags.map((v) => v!.toJson()).toList();
  //   }
  //   data['job_type'] = this.jobType;
  //   data['publication_date'] = this.publicationDate;
  //   data['candidate_required_location'] = this.candidateRequiredLocation;
  //   data['salary'] = this.salary;
  //   data['description'] = this.description;
  //   data['company_logo_url'] = this.companyLogoUrl;
  //   return data;
  // }
}
