import 'package:flutter/material.dart';
import 'package:future_to_provider/provider/provider_job_details.dart';
import 'package:future_to_provider/widgets/job_list.dart';
import 'package:future_to_provider/provider/provider_job.dart';
import 'package:future_to_provider/screens/job_list_detail_screen.dart';
import 'package:provider/provider.dart';

//import '../widget/detailscreen.dart';
class JobScreen1 extends StatefulWidget {
  // const JobScreen({Key? key}) : super(key: key);
  // @override
  static const routeName = '/job_screen';
  @override
  _JobScreen1State createState() => _JobScreen1State();
}

class _JobScreen1State extends State<JobScreen1> {
  var isloading = true;
  @override
  void initState() {
    super.initState();

    Provider.of<PrividerJob1>(context, listen: false)
        .fetchAutogenerated()
        .then((_) {
      setState(() {
        isloading = false;
      });
    });
    Provider.of<PrividerJob2>(context, listen: false)
        .fetchAutogenerated()
        .then((_) {
      setState(() {
        // isloading = false;
      });
    });
  }

  @override
  Widget build(BuildContext context) {
    final productdata = Provider.of<PrividerJob1>(context, listen: false);
    final products = productdata.list;
    return Scaffold(
      appBar: AppBar(
        title: const Text('First Flutter Application'),
        actions: [
          IconButton(
            onPressed: () {
              Navigator.of(context).pushNamed(JobScreen2.routeName);
            },
            icon: Icon(
              Icons.arrow_forward_ios_rounded,
            ),
          )
        ],
      ),
      body: isloading
          ? Center(child: CircularProgressIndicator())
          : ListView.builder(
              itemCount: products.length,
              itemBuilder: (ctx, index) =>
                  JobListWidget((index + 1).toString(), products[index].name)),
      floatingActionButton: FloatingActionButton(
        onPressed: () {
          setState(() {});
        },
      ),
    );
    //https://picsum.photos/200/300
  }
}
